/**
 * style-dictionary.config.mjs
 *
 * Source: tokens/source/tokens-studio.json (Tokens Studio canonical export)
 * Uses @tokens-studio/sd-transforms for math, composite tokens, and TS types.
 *
 * Responsibility: generate src/tokens/generated/tokens.ts
 *   — typed CSS custom property name constants for all foundation tokens
 *   — resolved values via the full 6-hop alias chain (light + neutral + laptop)
 *
 * CSS generation is handled separately by:
 *   figma-console-mcp (tokens/generated/*.css) — multi-mode, scheme-aware CSS
 *   tokens/build.mjs — defaults.css re-scoped to :root
 */

import StyleDictionary from 'style-dictionary';
import { register, expandTypesMap } from '@tokens-studio/sd-transforms';
import { readFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

register(StyleDictionary);

// ── Load the Tokens Studio JSON ──────────────────────────────────────
const tsJson = JSON.parse(
  readFileSync(path.join(__dirname, 'tokens/source/tokens-studio.json'), 'utf8')
);
const { $metadata: _, ...tokenSets } = tsJson;

// ── Deep merge selected sets into a flat SD token tree ───────────────
function deepMerge(target, source) {
  for (const [k, v] of Object.entries(source)) {
    if (v && typeof v === 'object' && !Array.isArray(v) && v.value === undefined) {
      target[k] ??= {};
      deepMerge(target[k], v);
    } else {
      target[k] = v;
    }
  }
  return target;
}

function mergeSets(setNames) {
  return setNames.reduce((acc, name) => {
    const set = tokenSets[name];
    if (!set) console.warn(`⚠  token set "${name}" not found`);
    else deepMerge(acc, set);
    return acc;
  }, {});
}

// ── Active sets for the default (light / neutral / laptop) context ────
// Mirrors the $metadata.tokenSetOrder with the standard active combination.
const activeSets = [
  'core',
  'foundation',
  'mode/light',
  'scheme/neutral',
  'white',
  'black',
  'brand',
  'secondary/primary',
  'restrictions/unrestricted',
  'breakpoint/laptop',
  'layout/layout',
];

// ── TypeScript formatter ──────────────────────────────────────────────
StyleDictionary.registerFormat({
  name: 'radd/ts-token-names',
  format: ({ dictionary }) => {
    const root = {};

    for (const token of dictionary.allTokens) {
      // Strip leading 'foundation' segment (colours-basic-accent not foundation-colours-basic-accent)
      const parts = [...token.path];
      if (parts[0] === 'foundation') parts.shift();

      let node = root;
      for (let i = 0; i < parts.length - 1; i++) {
        node[parts[i]] ??= {};
        node = node[parts[i]];
      }
      node[parts[parts.length - 1]] = `var(--${token.name})`;
    }

    function serialize(obj, indent = 2) {
      const pad = ' '.repeat(indent);
      return Object.entries(obj).flatMap(([k, v]) => {
        const key = /[^a-zA-Z0-9_$]/.test(k) ? `'${k}'` : k;
        if (typeof v === 'string') return [`${pad}${key}: '${v}',`];
        return [`${pad}${key}: {`, ...serialize(v, indent + 2), `${pad}},`];
      });
    }

    return [
      '// Auto-generated by style-dictionary — do not edit by hand.',
      '// Source: tokens/source/tokens-studio.json → RADD 2.0 Foundations',
      '// Active sets: light mode · neutral scheme · laptop breakpoint',
      '',
      'export const tokens = {',
      ...serialize(root),
      '} as const;',
      '',
      'export type Token = string;',
    ].join('\n');
  },
});

// ── Name transform: kebab + strip foundation prefix ───────────────────
StyleDictionary.registerTransform({
  name: 'radd/name-kebab',
  type: 'name',
  transform: (token) => {
    const parts = [...token.path];
    if (parts[0] === 'foundation') parts.shift();
    return parts
      .join('-')
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '');
  },
});

// ── Build ─────────────────────────────────────────────────────────────
mkdirSync(path.join(__dirname, 'src/tokens/generated'), { recursive: true });

const sd = new StyleDictionary({
  tokens: mergeSets(activeSets),
  preprocessors: ['tokens-studio'],
  expand: { typesMap: expandTypesMap },
  log: {
    warnings: 'warn',
    verbosity: 'default',
    errors: { brokenReferences: 'warn' },
  },
  platforms: {
    ts: {
      // ts/resolveMath handles "4*{dimension.base}" expressions
      transforms: ['ts/resolveMath', 'ts/size/px', 'ts/typography/fontWeight', 'radd/name-kebab'],
      buildPath: path.join(__dirname, 'src/tokens/generated') + '/',
      files: [
        {
          destination: 'tokens.ts',
          format: 'radd/ts-token-names',
          // Only export the foundation consumption layer
          filter: (token) => {
            const top = token.path[0];
            return (
              top === 'foundation' ||
              ['colours', 'spacing', 'sizing', 'radius', 'strokes', 'typography', 'elevation', 'grid'].includes(top)
            );
          },
        },
      ],
    },
  },
});

await sd.buildAllPlatforms();
console.log('✔  style-dictionary build complete (tokens.ts)');
