import StyleDictionary from 'style-dictionary';
import { glob } from 'node:fs/promises';
import path from 'node:path';

// ── Custom formatter: CSS custom property name constants ─────────────
// Outputs a typed TS module where each foundation token maps to
// its var(--...) reference string — enabling autocomplete in components.
StyleDictionary.registerFormat({
  name: 'radd/ts-token-names',
  format: ({ dictionary }) => {
    const lines = [
      '// Auto-generated by style-dictionary — do not edit by hand.',
      '// Source: Figma → System Flow RADD 2.0 Foundations',
      '',
      'export const tokens = {',
    ];

    // Build nested object from flat token list
    const root = {};
    for (const token of dictionary.allTokens) {
      const parts = token.path;
      let node = root;
      for (let i = 0; i < parts.length - 1; i++) {
        const key = parts[i];
        node[key] = node[key] || {};
        node = node[key];
      }
      const last = parts[parts.length - 1];
      const cssVar = `var(--${token.name})`;
      node[last] = cssVar;
    }

    function serialize(obj, indent = 2) {
      const pad = ' '.repeat(indent);
      const lines = [];
      for (const [k, v] of Object.entries(obj)) {
        const key = /[^a-zA-Z0-9_$]/.test(k) ? `'${k}'` : k;
        if (typeof v === 'string') {
          lines.push(`${pad}${key}: '${v}',`);
        } else {
          lines.push(`${pad}${key}: {`);
          lines.push(...serialize(v, indent + 2));
          lines.push(`${pad}},`);
        }
      }
      return lines;
    }

    lines.push(...serialize(root));
    lines.push('} as const;', '');
    lines.push('export type Token = string;');
    lines.push('export type TokenPath = keyof typeof tokens;');
    return lines.join('\n');
  },
});

// ── Name transform: kebab-case CSS custom property ───────────────────
StyleDictionary.registerTransform({
  name: 'radd/name-kebab',
  type: 'name',
  transform: (token) =>
    token.path
      .join('-')
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, ''),
});

// ── Config ───────────────────────────────────────────────────────────
const sd = new StyleDictionary({
  // All source files — required so aliases resolve across the full 6-hop chain
  source: [
    'tokens/source/core.sd.json',
    'tokens/source/white.sd.json',
    'tokens/source/black.sd.json',
    'tokens/source/brand.sd.json',
    'tokens/source/secondary.sd.json',
    'tokens/source/restricted.sd.json',
    'tokens/source/mode.sd.json',
    'tokens/source/scheme.sd.json',
    'tokens/source/breakpoint.sd.json',
    'tokens/source/layout.sd.json',
    'tokens/source/foundation.sd.json',
  ],

  log: {
    warnings: 'warn',
    verbosity: 'default',
    // Cross-library references (hover/pressed interaction states) are unresolvable
    // in this file — warn rather than throw so the build still produces output.
    errors: { brokenReferences: 'warn' },
  },

  platforms: {
    // TypeScript token name constants (foundation layer only)
    ts: {
      transforms: ['radd/name-kebab'],
      buildPath: 'src/tokens/generated/',
      files: [
        {
          destination: 'tokens.ts',
          format: 'radd/ts-token-names',
          // Only export the consumption layer — foundation tokens
          filter: (token) => {
            const src = token.filePath ?? '';
            return src.includes('foundation');
          },
          options: { outputReferences: false },
        },
      ],
    },
  },
});

await sd.buildAllPlatforms();
console.log('✔  style-dictionary build complete');
