/**
 * Post-process step: generates tokens/generated/defaults.css
 *
 * The figma-console-mcp CSS export scopes foundation tokens under
 * [data-theme="foundation"] and neutral scheme under [data-theme="neutral"].
 * This script re-declares both blocks on :root so that tokens work out of
 * the box without requiring data-theme wrappers — while still allowing
 * [data-theme="brand"] etc. to override schemes on nested elements.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const generated = path.join(__dirname, 'generated');

function reScope(file, fromSelector, toSelector = ':root') {
  const css = readFileSync(path.join(generated, file), 'utf8');
  return css
    .replace(/\/\* Generated.*?\*\/\n/, '')          // strip header comment
    .replace(new RegExp(escapeRe(fromSelector), 'g'), toSelector);
}

function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

const header = `/* Auto-generated by tokens/build.mjs — do not edit by hand.
 * Applies the neutral scheme and foundation layer to :root as the default,
 * so tokens work without data-theme wrapper elements.
 * Override a scheme on any element with [data-theme="brand"] etc.
 */\n\n`;

const defaultsCss =
  header +
  reScope('scheme.neutral.css', '[data-theme="neutral"]') +
  '\n\n' +
  reScope('foundation.foundation.css', '[data-theme="foundation"]');

const outPath = path.join(generated, 'defaults.css');
writeFileSync(outPath, defaultsCss);
console.log('✔  tokens/generated/defaults.css written');
