/**
 * Post-process step: generates tokens/generated/defaults.css
 *
 * The figma-console-mcp CSS export scopes every collection under a
 * [data-theme="..."] selector. This script re-declares all INTERMEDIATE
 * chain layers on :root so the full 6-hop alias chain resolves without
 * any wrapper elements.
 *
 * v2 alias chain (innermost first — each layer must be on :root):
 *   core (already :root) →
 *   leaf collections (white / black / brand / secondary) →
 *   restrictions (unrestricted) →
 *   mode (light default) →
 *   scheme (neutral default) →
 *   foundation (consumption layer)
 *
 * Override a scheme on any container: [data-theme="brand"]
 * Override dark mode on any container: .dark
 * Override breakpoint on any container: [data-theme="s-mobile"] etc.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const generated = path.join(__dirname, 'generated');

function reScope(file, fromSelector, toSelector = ':root') {
  const css = readFileSync(path.join(generated, file), 'utf8');
  return css
    .replace(/\/\* Generated.*?\*\/\n/, '')
    .replace(new RegExp(escapeRe(fromSelector), 'g'), toSelector);
}

function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

const header = `/* Auto-generated by tokens/build.mjs — do not edit by hand.
 * Re-scopes all intermediate alias chain layers to :root so the full
 * 6-hop colour chain resolves without any data-theme wrappers.
 *
 * Chain resolved on :root (light + neutral + laptop defaults):
 *   core → leaves (white/black/brand/secondary) → restrictions (unrestricted)
 *   → mode (light) → scheme (neutral) → breakpoint (laptop) → foundation
 */\n\n`;

const defaultsCss =
  header +

  // ── Layer 2: Leaf collections ──────────────────────────────────────
  // These hold the actual palette values that restrictions point to.
  // ALL leaves must be on :root so the chain works in any context.
  reScope('white.white.css',       '[data-theme="white"]')     + '\n\n' +
  reScope('black.black.css',       '[data-theme="black"]')     + '\n\n' +
  reScope('brand.brand.css',       '[data-theme="brand"]')     + '\n\n' +
  reScope('secondary.primary.css', '[data-theme="primary"]')   + '\n\n' +

  // ── Layer 3: Restriction layer (unrestricted default) ─────────────
  // Routes each leaf bucket (white/black/brand/secondary) through the
  // permission layer. Default is unrestricted — all schemes allowed.
  reScope('restricted.unrestricted.css', '[data-theme="unrestricted"]') + '\n\n' +

  // ── Layer 4: Mode — light default (:root), dark override (.dark) ──
  // mode.light.css is already scoped to :root by figma-console-mcp.
  // mode.dark.css is already scoped to .dark — no re-scoping needed.

  // ── Layer 5: Scheme — neutral default ─────────────────────────────
  reScope('scheme.neutral.css', '[data-theme="neutral"]') + '\n\n' +

  // ── Layer 6: Breakpoint — L-laptop default ─────────────────────────
  reScope('breakpoint.l-laptop.css', '[data-theme="l-laptop"]') + '\n\n' +

  // ── Layer 7: Foundation — consumption layer ────────────────────────
  reScope('foundation.foundation.css', '[data-theme="foundation"]');

const outPath = path.join(generated, 'defaults.css');
writeFileSync(outPath, defaultsCss);
console.log('✔  tokens/generated/defaults.css written — full 6-hop chain on :root');
