/**
 * tokens/generate-themes.mjs
 *
 * Generates flat, fully-resolved theme CSS files — one per scheme × mode
 * combination. Each file sets --colours-* and other foundation tokens to
 * their ACTUAL values (no var() chain), so CSS custom property inheritance
 * works correctly for runtime theming.
 *
 * Why flat resolution is required:
 *   Chrome evaluates var() at the ELEMENT WHERE THE PROPERTY IS DEFINED.
 *   A chain like :root { --colours-X: var(--scheme-X) } cannot be
 *   overridden by changing --scheme-X on a child element — the substitution
 *   already happened at :root. Flat values bypass this limitation.
 *
 * Output files (imported by src/tokens/index.ts):
 *   tokens/generated/theme-neutral-light.css  → :root
 *   tokens/generated/theme-neutral-dark.css   → .dark
 *   tokens/generated/theme-inverted-light.css → [data-scheme="inverted"]
 *   tokens/generated/theme-inverted-dark.css  → [data-scheme="inverted"].dark
 *   tokens/generated/theme-brand-light.css    → [data-scheme="brand"]
 *   tokens/generated/theme-brand-dark.css     → [data-scheme="brand"].dark
 *   tokens/generated/theme-secondary-light.css → [data-scheme="secondary"]
 *   tokens/generated/theme-secondary-dark.css  → [data-scheme="secondary"].dark
 *   tokens/generated/theme-white-light.css     → [data-scheme="white"]
 *   tokens/generated/theme-black-light.css     → [data-scheme="black"]
 */

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.join(__dirname, 'generated');

// ── Parse all generated CSS into a flat var map ──────────────────────
// key: css-var-name, value: Map<selector, value>
function parseCSS(filename) {
  const text = readFileSync(path.join(srcDir, filename), 'utf8')
    .replace(/\/\*.*?\*\//gs, '');
  const map = new Map(); // selector → Map<name, value>
  for (const block of text.matchAll(/([^{]+)\{([^}]+)\}/g)) {
    const selector = block[1].trim();
    const vars = new Map();
    for (const decl of block[2].matchAll(/--([a-z0-9-]+)\s*:\s*([^;]+);/g)) {
      vars.set(decl[1], decl[2].trim());
    }
    if (vars.size) map.set(selector, vars);
  }
  return map;
}

// Build combined flat lookup: varName → value per source file
function buildLookup(files) {
  const lookup = new Map(); // varName → resolved value
  for (const f of files) {
    try {
      const parsed = parseCSS(f);
      for (const [, vars] of parsed) {
        for (const [name, val] of vars) {
          lookup.set(name, val);
        }
      }
    } catch { /* file may not exist */ }
  }
  return lookup;
}

// Resolve a value through the var() chain (up to 12 hops)
function resolve(value, lookup, depth = 0) {
  if (depth > 12) return value;
  const ref = value.match(/^var\(--([a-z0-9-]+)\)$/);
  if (!ref) return value;
  const next = lookup.get(ref[1]);
  if (!next) return value; // unresolved ref — keep as-is
  return resolve(next, lookup, depth + 1);
}

// ── Foundation token names (the consumption layer) ───────────────────
// These are the vars components actually use.
function getFlatTheme(lookup) {
  const out = new Map();
  for (const [name, val] of lookup) {
    // Only output tokens that start with foundation category prefixes
    if (/^(colours|spacing|sizing|radius|strokes|typography|elevation|grid|layout)-/.test(name)) {
      const resolved = resolve(val, lookup);
      out.set(name, resolved);
    }
  }
  return out;
}

// Known dark-mode approximations for cross-library referenced tokens
// These come from the external ODS foundations library not included in our export.
// Values derived from the available core neutral palette.
const DARK_FALLBACKS = {
  // black.basic.background-subtle → neutral-900 equivalent in dark context
  'colours-basic-background-subtle':          '#2A2526',
  'colours-basic-background-card':            '#211C1E',
  // brand scheme dark — brand-dark palette background-subtle
  'colours-shades-accent-shades-accent-extra-dominant': '#FFCE01',
  'colours-shades-accent-shades-accent-dominant':        '#E6BA0A',
};

// Inverted scheme dark fallbacks
const INVERTED_DARK_FALLBACKS = {
  'colours-basic-background-subtle':  '#EBE6E8',
  'colours-basic-background-card':    '#DED5D7',
};

// Write a CSS file with a given selector
function writeTheme(filename, selector, varMap) {
  const lines = [`/* Auto-generated by tokens/generate-themes.mjs — do not edit */`, `${selector} {`];
  for (const [name, val] of varMap) {
    lines.push(`  --${name}: ${val};`);
  }
  lines.push('}', '');
  writeFileSync(path.join(srcDir, filename), lines.join('\n'));
  console.log(`✔  ${filename}  (${varMap.size} vars, selector: ${selector})`);
}

// ── Base files always loaded ─────────────────────────────────────────
const BASE = [
  'core.core.css',
  'white.white.css',
  'black.black.css',
  'brand.brand.css',
  'secondary.primary.css',
  'restricted.unrestricted.css',
  'breakpoint.l-laptop.css',
  'layout.columns.css',
];

// ── Generate each theme combination ──────────────────────────────────

const schemes = [
  { name: 'neutral',   schemeFile: 'scheme.neutral.css' },
  { name: 'inverted',  schemeFile: 'scheme.inverted.css' },
  { name: 'brand',     schemeFile: 'scheme.brand.css' },
  { name: 'secondary', schemeFile: 'scheme.secondary.css' },
  { name: 'white',     schemeFile: 'scheme.white.css' },
  { name: 'black',     schemeFile: 'scheme.black.css' },
];

const modes = [
  { name: 'light', modeFile: 'mode.light.css' },
  { name: 'dark',  modeFile: 'mode.dark.css'  },
];

console.log('Generating flat theme CSS...\n');

for (const scheme of schemes) {
  for (const mode of modes) {
    // white/black schemes are static (same in light and dark) — skip dark
    if ((scheme.name === 'white' || scheme.name === 'black') && mode.name === 'dark') {
      continue;
    }

    const files = [...BASE, scheme.schemeFile, mode.modeFile, 'foundation.foundation.css'];
    const lookup = buildLookup(files);
    let flat = getFlatTheme(lookup);

    // Remove vars that are still unresolved (contain var()) — they'll
    // fall through to the :root neutral-light value as a safe fallback.
    for (const [name, val] of flat) {
      if (val.startsWith('var(')) flat.delete(name);
    }

    // Apply known dark-mode approximations for cross-library tokens
    if (mode.name === 'dark') {
      const fb = scheme.name === 'inverted' ? INVERTED_DARK_FALLBACKS : DARK_FALLBACKS;
      for (const [name, val] of Object.entries(fb)) {
        if (!flat.has(name)) flat.set(name, val);
      }
    }

    const filename = `theme-${scheme.name}-${mode.name}.css`;

    let selector;
    if (scheme.name === 'neutral' && mode.name === 'light') {
      selector = ':root';
    } else if (scheme.name === 'neutral' && mode.name === 'dark') {
      selector = '.dark';
    } else if (mode.name === 'light') {
      selector = `[data-scheme="${scheme.name}"]`;
    } else {
      selector = `[data-scheme="${scheme.name}"].dark`;
    }

    writeTheme(filename, selector, flat);
  }
}

console.log('\n✔  All theme files written');
