/**
 * Token entry point — import this once at the top of your app / Storybook preview.
 *
 * Load order follows the v2 alias chain (innermost first):
 *   .core → leaves → restrictions → mode → schemes → foundation → breakpoints → defaults
 *
 * "defaults.css" re-scopes the neutral scheme + foundation layer onto :root so
 * tokens work without any wrapper element. Override a scheme anywhere with
 * [data-theme="brand"] etc. on a container element.
 */

// ── 1. Primitives ──────────────────────────────────────────────────────────
import '../../tokens/generated/core.core.css';

// ── 2. Leaf collections ────────────────────────────────────────────────────
import '../../tokens/generated/white.white.css';
import '../../tokens/generated/black.black.css';
import '../../tokens/generated/brand.brand.css';
import '../../tokens/generated/secondary.primary.css';

// ── 3. Restriction layer (unrestricted default) ────────────────────────────
import '../../tokens/generated/restricted.unrestricted.css';
import '../../tokens/generated/restricted.to-neutral.css';
import '../../tokens/generated/restricted.to-neutral-and-brand.css';
import '../../tokens/generated/restricted.to-neutral-and-secondary.css';

// ── 4. Mode layer (light on :root, dark on .dark) ─────────────────────────
import '../../tokens/generated/mode.light.css';
import '../../tokens/generated/mode.dark.css';

// ── 5. Scheme layer (override with [data-theme="<scheme>"]) ───────────────
import '../../tokens/generated/scheme.neutral.css';
import '../../tokens/generated/scheme.inverted.css';
import '../../tokens/generated/scheme.white.css';
import '../../tokens/generated/scheme.black.css';
import '../../tokens/generated/scheme.brand.css';
import '../../tokens/generated/scheme.secondary.css';

// ── 6. Foundation — consumption layer (what components reference) ──────────
import '../../tokens/generated/foundation.foundation.css';

// ── 7. Breakpoints ─────────────────────────────────────────────────────────
import '../../tokens/generated/breakpoint.s-mobile.css';
import '../../tokens/generated/breakpoint.m-tablet.css';
import '../../tokens/generated/breakpoint.l-laptop.css';
import '../../tokens/generated/breakpoint.xl-desktop.css';
import '../../tokens/generated/breakpoint.xxl-large-desktop.css';

// ── 8. Defaults — neutral + foundation scoped to :root ────────────────────
import '../../tokens/generated/defaults.css';

// ── Re-export typed token names (generated by style-dictionary) ───────────
export { tokens } from './generated/tokens';
export type { Token, TokenPath } from './generated/tokens';
